### ISSUE TITLE
Understanding .linearTrendLine?

### ISSUE THREAD

**Issue by gesabo** [willdale/SwiftUICharts-Demo#13]
Really enjoying this library!  Thanks for such excellent work! 🙌

I am trying to understand `.linearTrendLine.`  I see that it takes chartDate as a parameter, but then also takes a firstValue and lastValue.  As far as I can tell the line is just a straight line drawn from firstValue to lastValue?  

I was wondering if this was something you might come back to to add support for a trend line with curves more along the lines of a moving average?  I also tried `.averageLine` but this just gave me a flat horizontal line across the data.  

Thanks again for for a great library! 🍻

**Comment by willdale** [comment]
Hi,

Thanks you.

Can you move this to the main repo? It helps me keep track of everything, setup automation and helps others to find it.

Thanks

**Comment by gesabo** [comment]
Will do sorry!  didn't realize i was in the demo 🤦‍♂️
