### ISSUE TITLE
xAxisNumberOfLabels for BarChartStyle?

### ISSUE THREAD

**Issue by gesabo** [willdale/SwiftUICharts-Demo#16]
Is there no xAxisNumberOfLabels for BarChartStyle? If not any work around?  I have a Bar Chart with 60 data points but only want 5 labels so they can fit. 

Thanks!

**Comment by MasamMahmood** [comment]
@gesabo have you found the solution ?

**Comment by gesabo** [comment]
@MasamMahmood no I just input my own xAxisLabels into the chart and do all the math calculations, not ideal but works for now.

**Comment by MasamMahmood** [comment]
@gesabo - Right I am also thinking for my own custom calculations. Thank you.
