### ISSUE TITLE
Customize dot and markerType

### ISSUE THREAD

**Issue by BulatMukhutdinov** [willdale/SwiftUICharts-Demo#9]
Please, provide an API to 
1) customize `markerType`, especially color and stroke width. 
2) customize DotStyle - ideally, accept view builder.  At least change the way building dot. Now users could specify dot color and stroke. But it would be more flexible to set background color and radius and foreground color and radius.

Thanks

**Comment by willdale** [comment]
Can you move this over to the main Repo please?

[SwiftUICharts](https://github.com/willdale/SwiftUICharts-Demo/issues)
